apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc01
  namespace: java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mc01
  template:
    metadata:
      labels:
        app: mc01
    spec:
      containers:
        - name: memcached
          image: memcached
          ports:
            - containerPort: 11211
